baseURL = "https://dfkaye.com"
languageCode = "en-us"
title = "DFKaye"
theme = "dfkaye"

# Use absolute URLs
canonifyURLs = true

[permalinks]
  posts = "posts/:year/:month/:day/:slug/"

[params]
  author = "David F. Kaye"
  description = "Thoughts on building &amp; Testing JavaScript, CSS, HTML, et alâ€¦"
  siteStatus = "(conversion to Hugo in progress...)"
